import type { Metadata } from "next";
import "../globals.css";
import AuthLayoutProvider from "../components/Layout";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <AuthLayoutProvider>
            {children}
        </AuthLayoutProvider>
    )
}
